### ISSUE TITLE
Enable ARCore support for the Vuforia Engine

### ISSUE THREAD

**Issue by cmg7063** [cmg7063/IGME480FinalProject#25]

**Comment by cmg7063** [comment]
Build Settings > Player Settings > XR Settings > ARCore Supported

**Comment by cmg7063** [comment]
"Both ARCore and Vuforia XR Device support cannot be selected at the same time. Please select only one XR Device that will manage the Android device"

**Comment by kunstmusik** [comment]
See
https://library.vuforia.com/content/vuforia-library/en/articles/Solution/arcore-with-vuforia.html
